characterNames:
   - Adia
#   - Arandar
   - Bav
#   - Destronikus
   - Islar
#   - Jookie
#   - Jumaná
#   - Júmana
#   - Melissé
#   - Merò
#   - Sheywa
#   - Sàrin
#   - Vereesia
http:
   rootPath: /enwow/api/*
   port: 7070
   adminPort: 7071